### PR TITLE
feat: add toggle component

### PR DESCRIPTION
**Pull request by BerthaSoliany**
toggle without text
image
image

when disabled
image
image

toggle with text (right)
image
image
image

toggle with text (left)
image
image
image

### CODE REVIEW

**Comment by raflyhangga** [comment]
mergingnya ke development yak, bukan ke main

**Comment by BerthaSoliany** [comment]
kak, aku g paham knp dia conflict di lint-checks.yaml pdhl udh sama isinya

**Review by raflyhangga — APPROVED** [review]
LGTM!

**Comment by raflyhangga** [comment]
lain kali kalo mau bikin branch, checkoutnya dari development yakk

**Pull request merged**
