### PR TITLE
feat: footer

### PR DESCRIPTION
**Pull request by BerthaSoliany**
desktop
image

mobile
image

### CODE REVIEW

**Comment by raflyhangga** [comment]
mergingnya boleh di ganti ke development yak, bukan ke main

**Comment by raflyhangga** [comment]
image
Untuk import image, boleh pake komponen Imagenya Next JS yakk https://nextjs.org/docs/pages/building-your-application/optimizing/images

**Comment by BerthaSoliany** [comment]
done kak

**Review by raflyhangga — APPROVED** [review]
LGTM!

**Pull request merged**
